#
# Nmake file for mars2mseed - Windows version
# Use 'nmake -f Makefile.win'

NODEBUG=1

INCS = /I..\libmseed
OPTS = -D_CRT_SECURE_NO_WARNINGS
LIBS = ..\libmseed\libmseed.lib

BIN = ..\mars2mseed.exe

all: $(BIN)

$(BIN):	mars2mseed.obj marsio.obj
	link.exe /nologo /out:$(BIN) $(LIBS) mars2mseed.obj marsio.obj

.c.obj:
	$(CC) /nologo $(CFLAGS) $(INCS) $(OPTS) /c $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(BIN)
